### PR TITLE
Wp 1024 conn opt

### PR DESCRIPTION
**Pull request by habibvirji**
Connection optimization changes

Jira Issue: WP-1024

### CODE REVIEW

**Comment by TobyEalden** [comment]
This is working reliably for me on Windows and Linux...

**Comment by mlasak** [comment]
i've tested your PR. But there is an issue: Starting webinos_pzp.js for the first time works. After exiting and re-launching it, it will fail on my mac with, see https://gist.github.com/mlasak/fd8b02669f0c4e43da59 
I am with
 webinos-pzp on your WP-1024-conn-opt branch
 webinos-utilities on your master (you did a PR from your master ibtw)
 webinos-vertificateHandler on your WP-123-certifcate-parsing

**Comment by habibvirji** [comment]
Thanks martin, I have pushed a change to webinos-utilities as suggested by Alex. Tried on v0.10 without fix and it gives same error, after applying patch it seems to work. Please test and let me know how it goes.

**Comment by mlasak** [comment]
Hi Habib, the webinos-utilities patch works. Can restart the pzp now. However, the enrolment does not work. I started with a virgin state (.webinos and .webinosPzh deleted) and after finishing the enrolment procedure the pzp is show as orange(unconnected?) device in the pzh dashboard and on pzp dashboard at several places i see "undefined" in the ui and when trying to discover the test service only the one on pzp is found. Throughout all interactions at the pzp the is no activity in the pzh logs, even tough the pzp logs say "pzp_eventHandler.js(55) PZH_CONNECTED".

**Comment by habibvirji** [comment]
hi martin, have you used wp-1024 branch of webinos-pzh?

**Comment by mlasak** [comment]
Hi Habib, 
yes i'm on your WP-1024-conn-opt branch.
last commit ce0e4e56c0998f74efed72e10f8de579d52addf1

And in addition used same certificateHandler (73e3580731269b5aa9fca2feab61ccd0ffb14d0a) and utilities (commit d294fc80e0aa553df6b5aa371224ecf4a5008b18) from your branches as i used for the pzp.

Please shout if you need more information...

**Comment by aldafu** [comment]
@habibvirji, martin sees exactly the same behaviour i described in my email from wednesday. which is also why i'm surprised @TobyEalden got it working.

**Comment by habibvirji** [comment]
It is because you and martin are using v0.10 you get the error.

**Comment by TobyEalden** [comment]
I can confirm I'm still using node v0.8.15

**Comment by mlasak** [comment]
I've downgraded node to v0.8.25, then i had to rebuild the certificate certificateHandler and deleted .webinos/.webinosPzh. But still same error, enrolment procedure can be completed but the described issues remain. Dont't think that it's node version related. Could you maybe upgrade nodejs @TobyEalden and re-test to exclude that this is node version related?

**Comment by TobyEalden** [comment]
@mlasak I'm not in a position right now to change node versions, but I will do when I get a second. 

BTW, I'm running the PZH on Linux. Are you running the PZH on Windows or Linux?

**Comment by habibvirji** [comment]
Confirmed by Martin and Alex it works for them

**Pull request merged**
